[package]
name = "netsblox-vm-esp32"
version = "0.1.0"
authors = ["Devin Jean <emailcruzjean@yahoo.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dragazo/netsblox-vm-esp32"
documentation = "https://docs.rs/netsblox-vm-esp32"
description = "An implementation of netsblox-vm for esp32 embedded boards."

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
codegen-units = 1
lto = true

# remove this when rustlang team fixes this issue - https://github.com/rust-lang/compiler-builtins/issues/347
[profile.dev.package.compiler_builtins]
overflow-checks = false

[features]
pio = ["esp-idf-sys/pio"]

[dependencies]
netsblox-vm = { git = "https://github.com/dragazo/netsblox-vm", default-features = false, features = ["serde"] }
gc-arena = { git = "https://github.com/kyren/gc-arena", default-features = false }
esp-idf-sys = { version = "0.32.1", features = ["binstart"] }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc", features = ["experimental"] }
embedded-svc = { version = "0.24.0", feature = ["experimental"] }
esp-idf-hal = "0.40.1"
serde = { version = "1.0", features = ["derive"], default-features = false }
rand = { version = "0.8.5", default-features = false }
rand_chacha = { version = "0.3.1" }
getrandom = { version = "0.2.8" }
uuid = { version = "1.3.0", default-features = false, features = ["v4", "fast-rng"] }
string-ring = { version = "0.1.1", default-features = false }

[build-dependencies]
embuild = "0.31"
names = { version = "0.14.0", default-features = false }
serde = { version = "1.0", features = ["derive"], default-features = false }
toml = "0.7.3"
