[package]
name = "netsblox-vm-esp32c3"
version = "0.1.0"
authors = ["Devin Jean <emailcruzjean@yahoo.com>"]
edition = "2021"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
pio = ["esp-idf-sys/pio"]

[dependencies]
esp-idf-sys = { version = "0.32.1", features = ["binstart"] }
esp-idf-svc = { version = "0.45.0", features = ["experimental"] }
esp-idf-hal = "0.40.1"
embedded-svc = "0.24.0"
serde = { version = "1.0", features = ["derive"], default-features = false }
netsblox-vm = { git = "https://github.com/dragazo/NetsBlox-vm", default-features = false }

[build-dependencies]
embuild = "0.31"
