[i2c]
gpio = [17, 18]

[[motors]]
name = "LeftWheel"
gpio = [4, 5]

[[motors]]
name = "RightWheel"
gpio = [6, 7]

[[motor-groups]]
name = "Wheels"
motors = ["LeftWheel", "RightWheel"]

[[ultrasonic-distances]]
name = "Forward"
gpio = [15, 16]

[[digital-outs]]
name = "RedLedOn"
gpio = 14

[[digital-ins]]
name = "ButtonPressed"
gpio = 13
negated = true

[[max30205s]]
name = "Probe"
i2c-addr = 73
