name: Publish New Release
on:
  push:
    branches: ["master"]
permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install libudev-dev -y
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo install espup
      - run: espup install
      - run: cargo install espflash@2.0.0-rc.3
      - run: cargo +esp build --release
