name: Publish New Release
on:
  push:
    branches: ["master"]
permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: esp-rs/xtensa-toolchain@v1.5
      - uses: actions/setup-python@v5
      - run: sudo apt install -y libudev-dev
      - run: cargo install espflash
      - run: openssl req -newkey rsa:2048 -nodes -keyout privkey.pem -x509 -days 3650 -out cacert.pem -subj "/CN=NetsBlox VM ESP32"
      - run: mkdir pubs

      - run: cargo +esp build --release --target xtensa-esp32s3-espidf
      - run: espflash save-image --chip esp32s3 --flash-size 8mb --partition-table partitions.csv --merge target/xtensa-esp32s3-espidf/release/netsblox-vm-esp32 img
      - run: python extract-ota.py img partitions.csv ota
      - run: split -b 256k -da 4 ota ota-part-
      - run: ls ota-part-* | wc -l >ota-parts
      - run: mkdir pubs/esp32s3 && mv img pubs/esp32s3/. && mv ota pubs/esp32s3/. && mv ota-parts pubs/esp32s3/. && mv ota-part-* pubs/esp32s3/.

      - uses: actions/upload-pages-artifact@v3
        with:
          path: pubs
      - uses: actions/deploy-pages@v4
